version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=company-app'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: company_module
      MYSQL_USER: valet
      MYSQL_PASSWORD: secret
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3307:3307
